name: weather_overview
description: Weather overview app based on AirVisual API
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: 7.4.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 8.1.3
  freezed: 2.3.5
  get_it: 7.6.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  # intl is bounded with flutter_localizations
  intl: 0.18.0
  json_serializable: 6.7.0
  json_annotation: 4.8.1
  ntp: 2.0.0

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.4.5
  chopper_generator: 6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  flutter_gen_runner: 5.3.1
  freezed_annotation: 2.2.0
  hive_generator: 2.0.0
  intl_utils: 2.8.3
  mocktail: 0.3.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300

